version: "3.5"
services:
  beacon-chain:
    build:
      context: beacon-chain
      args:
        NETWORK: hoodi
        P2P_PORT: 9704
    ports:
      - "9704:9704/tcp"
      - "9704:9704/udp"
    environment:
      CORSDOMAIN: "http://lighthouse-hoodi.dappnode"
  validator:
    build:
      args:
        NETWORK: hoodi
